// PDF Generator Module

/**
 * Generate and download PDF report of results
 */
function generateResultsPDF(results) {
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();
    
    let yPosition = 20;
    const pageHeight = doc.internal.pageSize.height;
    const margin = 20;
    const lineHeight = 7;
    
    // Helper function to check if we need a new page
    function checkPageBreak(additionalHeight = 10) {
        if (yPosition + additionalHeight > pageHeight - margin) {
            doc.addPage();
            yPosition = margin;
            return true;
        }
        return false;
    }
    
    // Title
    doc.setFontSize(20);
    doc.setFont(undefined, 'bold');
    doc.text('UCEED 2026 Score Report', margin, yPosition);
    yPosition += 15;
    
    // Score Summary
    doc.setFontSize(14);
    doc.text('Score Summary', margin, yPosition);
    yPosition += 10;
    
    doc.setFontSize(11);
    doc.setFont(undefined, 'normal');
    doc.text(`Total Score: ${results.total_score.toFixed(2)}`, margin, yPosition);
    yPosition += lineHeight;
    doc.text(`Correct: ${results.total_correct}`, margin, yPosition);
    yPosition += lineHeight;
    doc.text(`Incorrect: ${results.total_incorrect}`, margin, yPosition);
    yPosition += lineHeight;
    doc.text(`Partial: ${results.total_partial}`, margin, yPosition);
    yPosition += lineHeight;
    doc.text(`Unattempted: ${results.total_unattempted}`, margin, yPosition);
    yPosition += lineHeight;
    doc.text(`Total Questions: ${results.total_questions}`, margin, yPosition);
    yPosition += 15;
    
    // Section-wise breakdown
    Object.values(results.sections).forEach(section => {
        checkPageBreak(20);
        
        // Section header
        doc.setFillColor(0, 0, 0);
        doc.rect(margin, yPosition - 5, 170, 10, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(12);
        doc.setFont(undefined, 'bold');
        doc.text(`${section.name} - ${section.score} marks`, margin + 2, yPosition + 2);
        doc.setTextColor(0, 0, 0);
        yPosition += 12;
        
        // Questions
        section.questions.forEach(q => {
            checkPageBreak(30);
            
            doc.setFontSize(10);
            doc.setFont(undefined, 'bold');
            
            // Question number and type
            const questionHeader = `Q.${q.question_number} [${q.question_type}]`;
            doc.text(questionHeader, margin, yPosition);
            yPosition += lineHeight;
            
            // Status
            const status = q.status === 'correct' || q.is_correct ? 'Correct' : 
                          q.status === 'partial' ? 'Partial' : 
                          q.status === 'unattempted' ? 'Unattempted' : 'Incorrect';
            doc.setFont(undefined, 'normal');
            doc.text(`Status: ${status}`, margin, yPosition);
            yPosition += lineHeight;
            
            // Question text (wrapped)
            doc.setFontSize(9);
            const questionLines = doc.splitTextToSize(q.question_text, 170);
            questionLines.forEach(line => {
                checkPageBreak();
                doc.text(line, margin, yPosition);
                yPosition += 5;
            });
            yPosition += 2;
            
            // Answers
            doc.setFontSize(9);
            doc.text(`Your Answer: ${formatAnswer(q.answer)}`, margin, yPosition);
            yPosition += lineHeight;
            doc.text(`Correct Answer: ${formatAnswer(q.correct_answer)}`, margin, yPosition);
            yPosition += lineHeight;
            doc.text(`Marks: ${q.marks} / ${q.max_marks}`, margin, yPosition);
            yPosition += 10;
        });
        
        yPosition += 5;
    });
    
    // Footer
    checkPageBreak(20);
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    yPosition = pageHeight - 15;
    doc.text('Generated by UCEED 2026 Score Calculator', margin, yPosition);
    yPosition += 5;
    doc.text('© beyondmebtw 2022-present | Created by Pranav Veeraghanta', margin, yPosition);
    
    // Save the PDF
    const fileName = `UCEED_2026_Results_${new Date().getTime()}.pdf`;
    doc.save(fileName);
}
